[tool.poetry]
name = "objectdetector"
version = "0.1.0"
description = "Wraps a state-of-the-art detection model and communicates on its inputs and outputs following visionapi."
authors = ["flonix8 <flstanek@googlemail.com>"]
license = "GPL3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ultralytics = "^8.0.97"
pydantic = "^1.10.7"
visionapi = { git = "git@github.com:starwit/vision-api.git", subdirectory = "python/visionapi", develop = true }
# This is a terrible, terrible hack. See: https://github.com/python-poetry/poetry/issues/6409
torch = { path = ".torchwheels/torch-2.0.1+cu118-cp310-cp310-linux_x86_64.whl" }
torchvision = { path = ".torchwheels/torchvision-0.15.2+cu118-cp310-cp310-linux_x86_64.whl" }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
